# Test 2025-03-30 at 03:59:55

name: Test
run-name: quickSortFailure

on:
  push

jobs:

  test:
    permissions: write-all
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: perl quickSortEasy.pl
      continue-on-error: true
      run: |
        echo "AAAA  $GITHUB_WORKSPACE"
        echo "BBBB $GITHUBWORKSPACE"
        #docker run --rm --env-file <(env)  -v "$GITHUB_WORKSPACE":/workspace -w /workspace ubuntu:22.04 bash run.sh
