# Test 2025-03-30 at 03:12:23

name: Test
run-name: quickSortFailure

on:
  push:
    paths:
      - '**/main.yml'
jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: perl quickSortEasy.pl
      run: |
        perl quickSortEasy.pl

    - name: python3 quickSortEasy.py
      run: |
        python3 quickSortEasy.py

    - name: perl quickSort.pl
      run: |
        perl quickSort.pl
